server:
  port: 8888


app:
  api-prefix: /api


spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: identity_service
          uri: http://localhost:8080
          predicates:
            - Path=${app.api-prefix}/identity/**
          filters:
            - StripPrefix=1
        - id: profile_service
          uri: http://localhost:8081
          predicates:
            - Path=${app.api-prefix}/profile/user/**
          filters:
            - StripPrefix=1
        - id: video_service
          uri: http://localhost:8082
          predicates:
            - Path=${app.api-prefix}/video/**
          filters:
            - StripPrefix=1
        - id: post_service
          uri: https://imterest-be.fly.dev
          predicates:
            - Path=${app.api-prefix}/images/**
          filters:
            - StripPrefix=1