server:
  port: 8081
  servlet:
    context-path: /profile

spring:
  datasource:
    url: jdbc:postgresql://aws-0-ap-southeast-1.pooler.supabase.com:6543/postgres?user=postgres.ojtjepkbgyuysupjepnf&password=RICLb0k9PbkYXPbH
    driver-class-name: org.postgresql.Driver
  application:
    name: profile-service
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
cloudinary:
  cloud_name: dxgfsw9l0
  api_key:    839666635858452
  api_secret: oZmp-7UZwSt88FDRpuTSGk9JLf0
