server:
    port: 8083
    servlet:
        context-path: /event


spring:
    datasource:
        url: jdbc:postgresql://aws-0-ap-southeast-1.pooler.supabase.com:6543/postgres?user=postgres.ojtjepkbgyuysupjepnf&password=RICLb0k9PbkYXPbH&prepareThreshold=0
        driver-class-name: org.postgresql.Driver
    application:
        name: event-service
    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 10MB
    jpa:
        hibernate:
            ddl-auto: update
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true
        properties:
            hibernate:
                format_sql: true
    logging:
        level:
            org.springframework.messaging: DEBUG
            org.springframework.web.socket: DEBUG